name: Arduino
 
on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
  release:
    types:
      - created
 
jobs:
  build:
    runs-on: ubuntu-latest 

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@main
 
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install repo as library
        run: |
          mkdir -p "$HOME/Arduino/libraries"
          ln -s "$PWD" "$HOME/Arduino/libraries/."  
 
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli board listall
          arduino-cli core install esp32:esp32

      - name: Install libraries
        env:
          ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true
        run: |
          arduino-cli lib install ArduinoJson
          arduino-cli lib install --git-url https://github.com/domino4com/ILB.git
          arduino-cli lib install --git-url https://github.com/domino4com/IGA.git
          arduino-cli lib install --git-url https://github.com/domino4com/IWA.git

      - name: Compile Application
        run: arduino-cli compile --fqbn esp32:esp32:esp32 ./AppStandard --warnings more

