name: PlatformIO

on:
  push:
    paths:
      - .github/workflows/**
      - examples/**
      - src/**
  pull_request:
  release:
    types:
      - created
  schedule:
    - cron: '0 5 15 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      id: onefile
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install esptool
    - name: Install platformIO libraries
      run: pio lib install
    - name: Build application
      run: platformio run
    - name: Build single upload firmware
      run: | 
        esptool.py --chip ESP32 merge_bin -o fw.bin @flash_args 0x10000 .pio/build/esp32dev/firmware.bin
        # zip --junk-paths fw.zip fw.bin

    - name: Create Release
      id : create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: "${{ github.event.head_commit.message }}"
        release_name: Release ${{ github.event.head_commit.message }}
        draft: true
        prerelease: true

    - name: Upload Release Asset
      id : upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./fw.bin
        asset_name: fw.bin
        asset_content_type: application/zip

    # - name: Create tag
    #   uses: rickstaa/action-create-tag@v1
    #    : "tag_create"
    #   with:
    #     tag: "${{ github.event.head_commit.message }}"
    #     tag_exists_error: false
    #     message: "Latest release"
